### ISSUE TITLE
Does it still work with SF4?

### ISSUE THREAD

**Issue by mlopezgva** [qbbr/vim-symfony#3]
Hello.

I am new to Symfony, and I like to know if this plugin for the SF3 will work with SF4.

Thank you.

**Comment by qbbr** [comment]
@mlopezgva hi. Plugin is not 100% compatibility with SF4, jumps will not work. In the near future I will add. Snippet and Console still work fine. 🦉

**Comment by mlopezgva** [comment]
Thank you for the anwser and for the work done.
As I'm new to Symfony, I appreciate any help to dig into it, and using phpctags and this plugin really helps a lot.

I am closing the issue. Thanks again!
